config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Changes from Andrea for Devise build
  root to: "teams#index"
  devise_for :students
  devise_for :teachers

  resources :students do
    resources :notes
  end
  resources :teachers do
    resources :notes
  end

  resources :teams
  resources :rules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/approved_teacher.rb
class ApprovedTeacher < ApplicationRecord
  validates :code, :email, presence: true
end

app/models/detention.rb
class Detention < ApplicationRecord
  belongs_to :issuer, class_name: Teacher, foreign_key: :issuer_id
  belongs_to :student

  validates :issuer_id, :student_id, presence: true
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student

  validates :score, :student_id, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :noteable, polymorphic: true
  belongs_to :sender, polymorphic: true

  validates :content, :noteable_id, :sender_id, presence: true
end

app/models/rule.rb
class Rule < ApplicationRecord
  belongs_to :teacher

  validates :rule_string, presence: true, uniqueness: true
  #validates :attribute, :criteria, :value, :active, presence: true

  # def allows?(student_to_be_added, students_on_team)
  #   students = students_on_team
  #   students << student_to_be_added

  #   if self[:modifier] == 'number of' && self[:attribute] == students
  #     return true if eval eval "'#{students.length}' #{self[:criteria]} #{self[:value]}"
  #     return false
  #   end
  #   # students.each do |student|
  #   #   eval eval "#{student[self[:attribute]]} #{self[:criteria]} #{self[:value]}"
  #   # end

  # end
end

app/models/student.rb
class Student < User
  belongs_to :team
  has_many :grades
  has_many :detentions
  has_one :teacher, through: :team
  has_many :sent_notes, class_name: "Note", foreign_key: :sender_id
  has_many :received_notes, class_name: "Note", foreign_key: :noteable_id

  validates :grade_level, presence: true
  validates_inclusion_of :grade_level, in: 6..12
  validates_inclusion_of :shirt_size, in: %w(xs s m l xl xxl)
  validates_inclusion_of :administrator, in: [false]

end

app/models/teacher.rb
class Teacher < User
  has_many :rules
  has_many :detentions, foreign_key: :issuer_id
  has_one :team, foreign_key: :teacher_id
  has_many :received_notes, class_name: "Note", foreign_key: :noteable_id
  has_many :sent_notes, class_name: "Note", foreign_key: :sender_id
  has_many :students, through: :team

  # validates :administrator, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :teacher
  has_many :students


  validates :teacher, :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :password, :first_name, :last_name, :hero_name, :superpower, :gender, presence: true

  validates :email, uniqueness: true

   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :get_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.all
  end

  def show
  end

  def new
    if params[:student_id]
      @recipient = Student.find(params[:student_id])
      @route = student_notes_path
      @sender = Teacher.all.sample
    else
      @recipient = Teacher.find(params[:teacher_id])
      @route = teacher_notes_path
      @sender = Student.all.sample
    end
    @note = Note.new
  end

  def create
    @note = Note.create(note_params)
    redirect_to '/'
  end

  def edit
  end

  def update
    @note.update(note_params)
    @note.save
  end

  def destroy
  end

  def get_note
    @note = Note.find(params[:id])
  end

  private
    def note_params
      params.require(:note).permit(:content, :noteable_id, :sender_id, :noteable_type, :sender_type)
    end

end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  def index
    @rules = Rule.all
  end
  def new
    @rules = Rule.all
    @rule = Rule.new
  end
  def create
    @rule = Rule.new(rule_params)
    if @rule.save
      redirect_to new_rule_path
    else
      redirect_to new_rule_path
    end
  end

private
  def rule_params
    params.require(:rule).permit(:rule_string, :teacher_id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_teams, only: [:show, :edit, :update, :destroy]

  def index
    @teams = Team.all
  end

  def show

    @grades = @team.students.map {|i| i.grades[0]}
    @scores = @grades.map {|i| i.score }
    @total = @scores.inject(0){|sum,x| sum + x }

    @stats = {
      :avg => @total / @team.students.count
    }

    @rules = Rule.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.create(teacher_params)
  end

  def edit
  end

  def update
    @team.update(teacher_params)
    @team.save
  end

  def destroy
  end

  def get_teams
    @team = Team.find(params[:id])
  end

  private
    def team_params
      params.require(:team).permit(:name, :teacher_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/detentions_helper.rb
module DetentionsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/notes/_note.html.erb
<div>
  <%= note.content %>
  - <%= note.sender.first_name + ' ' + note.sender.last_name %>
  <hr/>
</div>

app/views/notes/new.html.erb
<h1>Write a Note to <%= @recipient.first_name + ' ' + @recipient.last_name %></h1>
<%= form_for(@note, url: @route, method: 'post') do |f| %>
  <%= f.hidden_field :noteable_type, :value => @recipient.type %>
  <%= f.hidden_field :noteable_id, :value => @recipient.id %>
  <%= f.hidden_field :sender_type, :value => @sender.type %>
  <%= f.hidden_field :sender_id, :value => @sender.id %>
  <%= f.label :content %><br/>
  <%= f.text_area :content %><br/>
  <%= f.submit 'Send Note' %>
<% end %>

app/views/rules/_form.html.erb
<%= form_for(:rule, url: rules_path, method: 'post') do |r| %>
  Rule: <br><%= r.text_area :rule_string %><br>
  <%= r.hidden_field :teacher_id, :value => 1 %>
  <!-- Attribute : <#%= r.text_field :attribute %><br> -->
  <!-- Value     : <#%= r.text_field :value %><br> -->
  <!-- Criteria  : <#%= r.text_field :criteria %><br> -->
  <!-- Modifier  : <#%= r.text_field :modifier %><br> -->
  <!-- Active?   : <#%= r.check_box :active %><br> -->
  <%= r.submit %>
<% end %>

app/views/rules/_list.html.erb
<% if @rules.length == 0 %>
  <h5>NO CURRENT RULES</h5>
<% else %>
  <ul>
  <% @rules.each do |rule| %>
    <li>"<%= rule.rule_string %>" - <%= rule.teacher.hero_name %></li>
  <% end %>
  </ul>
<% end %>

app/views/rules/index.html.erb
<h1>Official Team Rules</h1>
<%= render partial: "list", object: @rules %>

<!--NEED TO ADD % SIGNS < if admin > -->
    <%= link_to 'Add New Rule', new_rule_path %>
  <!-- < else > -->
    <!-- <p>Please see admin for any information on rules</p> -->
<!-- < end > -->

app/views/rules/new.html.erb
<%= render partial: "list", object: @rules %>
<h1>Create new rule:</h1>
<%= render partial: "form"%>