config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Changes from Andrea for Devise build
  root to: "teams#index"
  devise_for :students
  devise_for :teachers

  resources :students do
    resources :notes
  end
  resources :teachers do
    resources :notes
  end

  resources :teams
  resources :rules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/approved_teacher.rb
class ApprovedTeacher < ApplicationRecord
  validates :code, :email, presence: true
end

app/models/detention.rb
class Detention < ApplicationRecord
  belongs_to :issuer, class_name: Teacher, foreign_key: :issuer_id
  belongs_to :student

  validates :issuer_id, :student_id, presence: true
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student

  validates :score, :student_id, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :noteable, polymorphic: true
  belongs_to :sender, polymorphic: true

  validates :content, :noteable_id, :sender_id, presence: true
end

app/models/rule.rb
class Rule < ApplicationRecord
  belongs_to :teacher

  validates :rule_string, presence: true, uniqueness: true
  #validates :attribute, :criteria, :value, :active, presence: true

  # def allows?(student_to_be_added, students_on_team)
  #   students = students_on_team
  #   students << student_to_be_added

  #   if self[:modifier] == 'number of' && self[:attribute] == students
  #     return true if eval eval "'#{students.length}' #{self[:criteria]} #{self[:value]}"
  #     return false
  #   end
  #   # students.each do |student|
  #   #   eval eval "#{student[self[:attribute]]} #{self[:criteria]} #{self[:value]}"
  #   # end

  # end
end

app/models/student.rb
class Student < User
  belongs_to :team
  has_many :grades
  has_many :detentions
  has_one :teacher, through: :team
  has_many :sent_notes, class_name: "Note", foreign_key: :sender_id
  has_many :received_notes, class_name: "Note", foreign_key: :noteable_id

  validates :grade_level, presence: true
  validates_inclusion_of :grade_level, in: 6..12
  validates_inclusion_of :shirt_size, in: %w(xs s m l xl xxl)
  validates_inclusion_of :administrator, in: [false]

end

app/models/teacher.rb
class Teacher < User
  has_many :rules
  has_many :detentions, foreign_key: :issuer_id
  has_one :team, foreign_key: :teacher_id
  has_many :received_notes, class_name: "Note", foreign_key: :noteable_id
  has_many :sent_notes, class_name: "Note", foreign_key: :sender_id
  has_many :students, through: :team

  # validates :administrator, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :teacher
  has_many :students


  validates :teacher, :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :password, :first_name, :last_name, :hero_name, :superpower, :gender, presence: true

  validates :email, uniqueness: true

   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :get_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.all
  end

  def show
  end

  def new
    if params[:student_id]
      @recipient = Student.find(params[:student_id])
      @route = student_notes_path
      @sender = Teacher.all.sample
    else
      @recipient = Teacher.find(params[:teacher_id])
      @route = teacher_notes_path
      @sender = Student.all.sample
    end
    @note = Note.new
  end

  def create
    @note = Note.create(note_params)
    redirect_to '/'
  end

  def edit
  end

  def update
    @note.update(note_params)
    @note.save
  end

  def destroy
  end

  def get_note
    @note = Note.find(params[:id])
  end

  private
    def note_params
      params.require(:note).permit(:content, :noteable_id, :sender_id, :noteable_type, :sender_type)
    end

end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  def index
    @rules = Rule.all
  end
  def new
    @rules = Rule.all
    @rule = Rule.new
  end
  def create
    @rule = Rule.new(rule_params)
    if @rule.save
      redirect_to new_rule_path
    else
      redirect_to new_rule_path
    end
  end

private
  def rule_params
    params.require(:rule).permit(:rule_string, :teacher_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/detentions_helper.rb
module DetentionsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>X-School</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag :application, "//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag :application, "//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js" %>

  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">X-School</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="/teams">Teams</a>
            <a class="nav-item nav-link" href="/teachers">Teachers</a>
            <a class="nav-item nav-link" href="/students">Students</a>
            <% if student_signed_in?  %>
              <a class="nav-item nav-link" href="/students/ %>">Profile</a>
            <% elsif teacher_signed_in? %>
              <a class="nav-item nav-link" href="/teachers/">Profile</a>
            <% end %>

            <% if student_signed_in? %>
            <%= button_to 'Log out', destroy_student_session_path, method: :delete, :class => "nav-item nav-link" %>
            <% end %>
            <% if teacher_signed_in? %>
            <%= button_to 'Log out', destroy_teacher_session_path, method: :delete, :class => "nav-item nav-link" %>
            <% end %>

          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="application_flash">
        <%= notice %>
        <%= alert %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>